Update rust container image
This should fix error:

error: failed to get `ansi_colours` as a dependency of package `git-delta v0.1.1 (/builds/morawskim/rpm-pipeline/delta-0.1.1)`
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  error reading from the zlib stream; class=Zlib (5)